#!/usr/bin/env sh

LINES=25
case "$1" in
	*.png|*.jpg|*.jpeg|*.mkv|*.mp4|*.mp3|*.m4a|*.webm) mediainfo "$1";;
	*.md) glow -s dark "$1";;
	*.pdf) pdfoftext "$1" -;;
	*.zip) zipinfo "$1";;
	*.tar.gz) tar -ztvf "$1";;
	*.tar.bz2) tar -jtvf "$1";;
	*.tar) tar -tvf "$1";;
	*.rar) unrar l "$1";;
	*.7z) 7z l "$1";;
	*.zsh|*.bash|*.git*|*.sh|*.conf|*rc|*config) pistol "$1";;		# check for pistol script
	#*) highlight "$1" -O ansi --force;;
	*) pistol "$1";;
esac
