#!/usr/bin/env bash
#     _    ____  ____
#    / \  / ___||  _ \   Abhay Shanker Pathak
#   / _ \ \___ \| |_) |  abhaysp9955@gmail.com
#  / ___ \ ___) |  __/   https://github.com/coolabhays
# /_/   \_\____/|_|
#
# another preview file for lf

set -C -f -u
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"


# ANSI color codes are supported
# STDIN is disabled, so interactive scripts won't work properly

# Meanings of exit codes:

# code | Meaning    | Action
# -----+------------+--------
# 0    | success    | Display stdout as preview
# 1    | no preview | Display no preview at all
# 2    | plain text | Display the plain content of the file

# script arguments
FILE_PATH="${1}"  # full path of highlighted file
HEIGHT="${2}"

FILE_EXTENSION="${FILE_PATH##*.}"
FILE_EXTENSION_LOWER=$(echo ${FILE_EXTENSION} | tr '[:upper:]' '[:lower:]')


# settings
HIGHLIGHT_SIZE_MAX=262143  # 256kib
HIGHLIGHT_TABWIDTH=8
HIGHLIGHT_STYLE='pablo'


handle_mime() {
	local mimetype="${1}"
	case "${mimetype}" in
		text/html) w3m -dump "${FILE_PATH}" ;;
		text/troff) man ./ "${FILE_PATH}" | col -b ;;
		text/* | */xml)
			if [ "$( stat --printf='%s' -- "${FILE_PATH}" )" -gt "${HIGHLIGHT_SIZE_MAX}" ]; then
				exit 2
			fi
			if [ "$( tput colors )" -ge 256 ]; then
				local highlight_format='xterm256'
			else
				local highlight_format='ansi'
			fi
			highlight --replace-tabs="${HIGHLIGHT_TABWIDTH}" --out-format="${highlight_format}" \
				--style="${HIGHLIGHT_STYLE}" --force -- "${FILE_PATH}" ;;
		application/zip) atool --list -- "${FILE_PATH}" ;;
		image/*) chafa --fill=block --symbols=block -c 256 -s 80x"${HEIGHT}" "${FILE_PATH}" || exit 1;;
		video/* | audio/*|application/octet-stream) mediainfo "${FILE_PATH}" || exit 1;;
		*/pdf) pdftotext -l 10 -nopgbrk -q -- "${FILE_PATH}" - ;;
		*opendocument*) odt2txt "${FILE_PATH}" ;;
	esac
}

MIMETYPE="$( file --dereference --brief --mime-type -- "{FILE_PATH}" )"
handle_mime "${MIMETYPE}"
exit 1
