#! /bin/sh

bspc rule -r "*"

###---Autostart---###
# nm-applet &
# xrdb ~/.Xresources &
# nitrogen --set-scaled --head=0 ~/.config/wall.png &
# nitrogen --set-scaled --head=1 ~/.config/wall.png &
# killall cleanfullscreen
# cleanfullscreen &
#killall "launchlemon"
#launchlemon &
~/.config/polybar/./launch.sh

###---MONITORS---###
my_monitor="$(bspc query --monitors --names)"
bspc monitor "$my_monitor" -d 1 2 3 4 5 6 7 8 9 0

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier control
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color   "#282c34"
bspc config active_border_color   "#282c34"
bspc config focused_border_color  "#a5f2d1"
bspc config presel_feedback_color "#5e81ac"
# bspc config urgent_border_color   "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 15
bspc config bottom_padding 2
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.55
bspc config borderless_monocle true
# bspc config gapless_monocle true

###---Rules---###
bspc rule -a mpv state=fullscreen
# bspc rule -a Zathura state=floating
bspc rule -a Zathura desktop='^9'
bspc rule -a qutebrowser desktop='^2'
bspc rule -a mpv desktop='^4'
bspc rule -a TelegramDesktop desktop='^7'
bspc rule -a Lxappearance desktop='^7'
bspc rule -a Pcmanfm desktop='^8'
bspc rule -a Nautilus desktop='^8'
bspc rule -a Gcolor3 state=floating
bspc rule -a Screenkey manage=off rectangle=300x150+500+50
# bspc rule -a guvcview state=floating rectangle=480x270+1440+810 sticky=on layer=above
