#!/usr/bin/env bash
#     _    ____  ____
#    / \  / ___||  _ \   Abhay Shanker Pathak
#   / _ \ \___ \| |_) |  abhaysp9955@gmail.com
#  / ___ \ ___) |  __/   https://github.com/coolabhays
# /_/   \_\____/|_|
#
# bspwm config file


GAP=6

bspc rule -r "*"

###---Autostart---###
~/.config/polybar/./launch.sh

###---MONITORS---###
my_monitor="$(bspc query --monitors --names)"
#bspc monitor "$my_monitor" -d 1 2 3 4 5 6 7 8 9
#bspc monitor "$my_monitor" -d                
#bspc monitor "$my_monitor" -d         
bspc monitor "$my_monitor" -d         
###---Global Settings---###

# spawns new node on left with spiral
bspc config automatic_scheme spiral
bspc config initial_polarity first_child

bspc config external_rules_command "$HOME"/.config/bspwm/scratchpads.sh

# mouse actions
bspc config pointer_modifier control
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# coloring
bspc config normal_border_color   "#000000"
bspc config active_border_color   "#000000"
bspc config focused_border_color  "#d3d7cf"
bspc config focused_locked_border_color "#00ff00"
bspc config focused_private_border_color "#504339"
bspc config active_locked_border_color "#ff0000"
bspc config presel_feedback_color "#555753"
bspc config normal_frame_opacity 1.0
bspc config focused_frame_opacity 0.0

###---Monitor And Desktop Settings----###
bspc config top_padding 16
bspc config bottom_padding 16
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 1
bspc config window_gap "${GAP}"
bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config leaf_monocle true
bspc config adaptive_raise true
bspc config apply_floating_atom true
bspc config history_aware_focus true

###---Rules---###
bspc rule -a Zathura desktop='^9' state=floating
bspc rule -a qutebrowser desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a Vivaldi-stable desktop='^2'
bspc rule -a Chromium private=on
bspc rule -a mpv desktop='^4' state=fullscreen
bspc rule -a Uget-gtk desktop='^6'
bspc rule -a TelegramDesktop desktop='^7'
bspc rule -a Lxappearance desktop='^7'
bspc rule -a Pcmanfm desktop='^8'
bspc rule -a Nautilus desktop='^8'
bspc rule -a Gcolor3 state=floating
bspc rule -a Screenkey manage=off rectangle=300x150+500+50

# bspc rule -a guvcview state=floating rectangle=480x270+1440+810 sticky=on layer=above
# bspc config external_rules_command external_rules.sh
# bspc config urgent_border_color   "#dd2727"
