# gruvbox material <<<
colors:
  primary:
    foreground : '0xd4be98'
    background : '0x1d2021'

  normal    :
    black   : '0x1d2021'
    red     : '0xea6962'
    green   : '0xa9b665'
    yellow  : '0xd8a657'
    blue    : '0x80aa9e'
    magenta : '0xd3869b'
    cyan    : '0x8bba7f'
    white   : '0xbdae93'

  bright    :
    black   : '0x928374'
    red     : '0xea6962'
    green   : '0xa9b665'
    yellow  : '0xd8a657'
    blue    : '0x80aa9e'
    magenta : '0xd3869b'
    cyan    : '0x8bba7f'
    white   : '0xd4be98'
