
# colors (uwu)
colors:
  # Default colors
  primary:
    background: '0x181f21'
    foreground: '0xdadada'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xd6d6d6'
    cursor: '0x3b4244'

  # Normal colors
  normal:
    black:   '0x22292b'
    red:     '0xe06e6e'
    green:   '0x8ccf7e'
    yellow:  '0xe5c76b'
    blue:    '0x67b0e8'
    magenta: '0xc47fd5'
    cyan:    '0x6da4cd'
    white:   '0xb3b9b8'

  # Bright colors
  bright:
    black:   '0x3b4244'
    red:     '0xef7d7d'
    green:   '0x9bdead'
    yellow:  '0xf4d67a'
    blue:    '0x6cb5ed'
    magenta: '0xce89df'
    cyan:    '0x67cbe7'
    white:   '0xbdc3c2'
